
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 88
#define YY_END_OF_BUFFER 89
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[424] =
    {   0,
       86,   86,   89,   88,   85,    2,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   87,    1,   85,    2,   87,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       11,   86,   86,   86,   86,   63,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,    1,   86,   86,
       86,   86,   86,   60,   86,   86,   86,   86,   86,   86,
       31,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   26,   86,   86,   32,   86,   86,   86,   86,

       86,   86,   86,   87,   86,   86,   30,   87,   86,   54,
       86,   14,   86,   86,    3,   49,   45,   48,   47,   86,
       86,   86,   12,   86,   86,   68,   13,   15,   86,   87,
       86,   86,   86,   86,   86,   17,   86,   87,   56,   87,
       41,   86,   86,   86,   86,   86,   73,   86,    5,   69,
       70,   71,   72,   86,   87,   86,   86,   25,   86,   87,
       86,   86,   86,   86,   87,   80,   87,   87,   87,   87,
       86,   10,   86,   86,   86,   86,   87,   87,   87,   87,
       87,   53,   86,   86,   86,   87,   87,   79,   87,   66,
        8,   24,   87,   87,   86,   40,   86,    4,   87,   87,

       87,   16,   87,   87,   87,   87,   86,   86,   87,   87,
       87,   87,   87,   42,   86,   62,   86,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   86,   81,   87,   87,   87,
       87,   43,    6,   87,   65,   87,   87,   87,   87,   87,
       87,   46,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,    7,   87,   87,
       87,   87,   87,   87,   87,   58,   87,   55,   87,   87,
       87,   87,   87,   87,   87,   87,   20,   87,   19,   87,
       87,   87,   87,   52,   33,   87,   36,   87,   87,   82,

       87,   59,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       29,   87,   27,    9,   51,   87,   87,   87,   87,   38,
       87,   87,   61,   87,   87,   87,   74,   75,   76,   77,
       87,   87,   87,   87,   87,   87,   18,   50,   87,   87,
       39,   87,   44,   87,   87,   28,   87,   87,   87,   87,
       87,   87,   87,   87,   35,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       57,   67,   87,   87,   87,   87,   34,   37,   83,   84,

       87,   87,   87,   87,   87,   64,   78,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   21,
       22,   23,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,    7,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   25,   32,   25,
        1,    1,    1,    1,   33,    1,   34,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[35] =
    {   0,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[427] =
    {   0,
        0,    0,  780,  781,  777,   32,   38,   70,   32,   39,
       88,   33,   34,   71,   67,   37,   66,   68,   73,   98,
      117,   41,   77,    0,    0,  776,  144,    0,   84,  106,
       97,  107,  126,  137,  139,  141,  112,  160,  108,  147,
      155,  163,  165,  164,  156,  166,  169,  170,  183,  189,
      185,  192,  193,  190,  196,  191,  206,  199,  223,  214,
      227,  222,  217,  232,  230,  246,  236,    0,  243,  247,
      249,  252,  221,  254,  257,  256,  265,  273,  279,  280,
      262,  281,  286,  276,  283,  294,  284,  297,  300,  308,
      305,  313,  303,  314,  316,  319,  321,  336,  323,  338,

      339,  340,  346,  773,  344,  359,  343,  373,  364,  353,
      366,  367,  372,  385,  368,  382,  383,  386,  388,  391,
      393,  390,  392,  406,  407,  408,  409,  410,  412,  429,
      428,  430,  432,  434,  436,  438,  449,  416,  451,  121,
      452,  453,  454,  467,  468,  457,    0,  458,  471,    0,
        0,    0,    0,  475,  752,  477,  482,  472,  481,   84,
      485,  491,  495,  501,  764,  492,  744,  744,  758,  743,
      498,  505,  506,  508,  509,  515,  753,  758,  759,  745,
      514,  516,  523,  531,  530,   93,  536,  533,  740,  537,
      538,  539,  748,  750,  540,  541,  546,  547,  747,  749,

      739,    0,  751,  732,  731,  557,  548,  557,  742,  733,
      726,  740,  739,    0,  565,  564,  570,  741,  719,  741,
      726,  731,  725,  732,  575,  426,  736,  722,  732,  714,
      713,  712,  713,  712,  724,  574,  571,  719,  713,  719,
      716,    0,  572,  721,  578,  722,  706,  717,  705,  704,
      709,    0,  716,  713,  713,  689,  688,  687,  697,  690,
      689,  703,  706,  705,  700,  703,  699,  581,  682,  676,
      695,  685,  686,  683,  691,    0,  691,    0,  675,  363,
      692,  683,  681,  680,  679,  681,    0,  678,    0,  666,
      665,  679,  669,    0,  657,  666,  655,  670,  669,    0,

      652,    0,  668,  664,  669,  659,  669,  650,  649,  648,
      663,  652,  661,  660,  650,  656,   59,  591,  660,  641,
      644,  646,  653,  648,  610,  228,  641,  636,  635,  634,
        0,  638,    0,    0,    0,  646,  638,  643,  642,    0,
      635,  641,    0,  602,  641,  630,    0,    0,    0,    0,
      630,  633,  627,  620,  619,  618,    0,    0,  628,  630,
        0,  626,    0,  624,  619,    0,  625,  618,  624,  615,
      603,  602,  601,  611,    0,  610,  608,  607,  620,  605,
      614,  613,  601,  600,  599,  603,  602,  594,  592,  591,
        0,    0,  598,  582,  580,  564,    0,    0,    0,    0,

      536,  501,  480,  460,  459,    0,    0,  425,  421,  377,
      332,  314,  312,  308,  305,  245,  148,  145,  119,    0,
        0,    0,  781,   91,   65,   45
    } ;

static yyconst flex_int16_t yy_def[427] =
    {   0,
      423,    1,  423,  423,  423,  424,  425,  425,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,  424,  426,  423,  424,  424,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,  426,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,  424,    8,    8,    8,  424,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,  424,
        8,    8,    8,    8,    8,    8,    8,  424,    8,  424,
        8,    8,    8,    8,    8,    8,  424,    8,    8,  424,
      424,  424,  424,    8,  424,    8,    8,    8,    8,  424,
        8,    8,    8,    8,  424,    8,  424,  424,  424,  424,
        8,    8,    8,    8,    8,    8,  424,  424,  424,  424,
      424,    8,    8,    8,    8,  424,  424,    8,  424,    8,
        8,    8,  424,  424,    8,    8,    8,    8,  424,  424,

      424,  424,  424,  424,  424,  424,    8,    8,  424,  424,
      424,  424,  424,  424,    8,    8,    8,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,    8,    8,  424,  424,  424,
      424,  424,    8,  424,    8,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,    8,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,    0,  423,  423,  423
    } ;

static yyconst flex_int16_t yy_nxt[816] =
    {   0,
        4,    5,    6,    6,    6,    6,    6,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   17,
       18,   16,   19,   16,   16,   20,   21,   22,   16,   23,
       16,   16,   24,   25,   27,   27,   27,   27,   27,   27,
       28,   28,   28,   28,   28,   28,   68,   37,   29,   44,
       29,   38,   45,   29,   36,   39,   47,   66,   30,   31,
       29,   46,   29,   32,   33,   29,   29,   29,  337,   29,
       28,   28,   28,   28,   28,   28,   28,   28,   53,   48,
       51,  338,   54,   29,   29,   67,   34,   49,   52,   29,
       55,   56,   28,   29,   29,   29,   29,  193,   35,   50,

       29,   29,   28,   28,   29,   29,  194,   40,   41,   42,
       57,   58,   29,   70,   29,   71,   29,   43,   69,  218,
      219,   82,   29,   29,   29,   29,   29,   59,   29,   60,
      422,   61,   62,   29,   29,   29,   29,  180,   63,   79,
       29,   72,   29,  181,   64,   65,   27,   27,   27,   27,
       27,   27,   73,   29,   29,   29,  421,   29,   75,  420,
       74,   77,   78,   29,   89,   29,   76,   29,   80,   29,
       81,   29,   29,   83,   85,   29,   29,   87,   84,   29,
       29,   29,   29,   29,   29,   29,   29,   90,   29,   88,
       86,   29,   29,   29,   29,   92,   91,   29,   29,   29,

       94,   29,   96,   98,   97,   29,   29,   29,   29,   29,
       93,   29,   29,   29,   95,  103,  100,   29,   29,   29,
       29,   29,   29,   99,   29,  101,  104,   29,  110,  108,
       29,  105,  102,   29,   29,  106,  351,  120,   29,   29,
      111,  107,   29,   29,  109,   29,   29,  352,   29,   29,
       29,   29,   29,  112,  116,   29,  113,  419,   29,   29,
       29,  115,   29,   29,   29,   29,  114,  117,   29,  118,
       29,   29,   29,   29,   29,   29,  121,   29,   29,  119,
       29,   29,   29,  122,   29,   29,  124,  125,  123,   29,
       29,  126,   29,   29,  127,   29,   29,   29,  128,   29,

       29,   29,   29,  129,   29,  132,  131,   29,   29,   29,
       29,   29,   29,   29,   29,  130,   29,  418,  135,   29,
      417,   29,   29,  133,   29,   29,  134,  136,   29,   29,
       29,   29,   29,   29,  137,   29,   29,   29,  416,   29,
      415,   29,   29,  139,   29,  142,  138,   29,  141,   29,
      143,   29,   29,  140,   29,   29,   29,  146,  414,   29,
       29,  144,   29,  145,   29,  148,   29,   29,   29,   29,
      149,   29,   29,  304,   29,   29,  150,  151,  152,  153,
       29,   29,   29,   29,   29,  155,  154,   29,   29,  305,
      158,  156,   29,  157,   29,   29,   29,  159,   29,   29,

       29,   29,   29,  413,   29,  162,   29,   29,   29,   29,
       29,   29,  163,   29,   29,  160,   29,  161,   29,   29,
       29,   29,  164,   29,   29,   29,   29,  177,   29,  256,
      257,  258,  178,  179,   29,   29,   29,   29,   29,  165,
       29,  167,  168,  166,   29,  169,   29,  412,   29,  174,
       29,  411,   29,  171,   29,  170,   29,  172,   29,  173,
       29,  176,   29,  175,   29,   29,   29,   29,   29,   29,
      183,  410,  409,   29,   29,  184,  185,   29,  182,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,  186,
      187,   29,  408,   29,  191,   29,   29,   29,   29,   29,

       29,   29,  188,   29,  190,   29,  192,   29,   29,   29,
       29,   29,  195,   29,   29,  198,  197,   29,  196,   29,
       29,   29,   29,   29,   29,  207,   29,  213,  407,   29,
      204,   29,   29,   29,   29,  214,   29,   29,  205,   29,
      206,  208,  216,   29,   29,  220,   29,   29,  406,   29,
      221,   29,  215,   29,   29,   29,   29,   29,   29,   29,
      217,   29,   29,   29,   29,   29,   29,   29,   29,   29,
      236,  233,  225,   29,   29,   29,   29,  243,  226,  234,
       29,   29,  235,  237,  253,   29,   29,   29,   29,  405,
       29,  245,   29,   29,   29,  268,  244,   29,   29,   29,

       29,  254,   29,  255,  339,  404,   29,  403,  402,   29,
      364,  401,  340,  347,  348,  349,  350,  400,  365,  399,
      398,  397,  396,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  346,  345,  344,  343,  342,  341,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,

      306,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  252,  251,  250,  249,  248,
      247,  246,  242,  241,  240,  239,  238,  232,  231,  230,
      229,  228,  227,  224,  223,  222,  212,  211,  210,  209,
      203,  202,  201,  200,  199,  189,  147,   26,   26,  423,
        3,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423
    } ;

static yyconst flex_int16_t yy_chk[816] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,  426,   10,    9,   12,
       13,   10,   12,   16,    9,   10,   13,   22,    7,    7,
        9,   12,   13,    7,    7,   16,  425,   10,  317,   22,
        7,    7,    8,    8,    8,    8,    8,    8,   17,   14,
       15,  317,   17,   15,   18,   23,    8,   14,   15,   19,
       18,   19,  424,   23,   17,   15,   18,  160,    8,   14,

       29,   19,    8,    8,   11,   23,  160,   11,   11,   11,
       20,   20,   29,   31,   20,   32,   11,   11,   30,  186,
      186,   39,   30,   32,   39,   31,   20,   21,   37,   21,
      419,   21,   21,   21,   30,   32,   39,  140,   21,   37,
       37,   33,   33,  140,   21,   21,   27,   27,   27,   27,
       27,   27,   33,   34,   33,   35,  418,   36,   35,  417,
       34,   36,   36,   40,   45,   34,   35,   35,   38,   36,
       38,   41,   45,   40,   42,   40,   38,   43,   41,   42,
       44,   43,   46,   41,   45,   47,   48,   46,   38,   44,
       42,   42,   44,   43,   46,   48,   47,   47,   48,   49,

       50,   51,   52,   54,   53,   50,   54,   56,   52,   53,
       49,   49,   55,   51,   50,   58,   57,   50,   54,   56,
       52,   53,   57,   55,   55,   57,   59,   58,   63,   61,
       60,   59,   57,   63,   57,   60,  326,   73,   62,   59,
       64,   60,   60,   61,   62,   63,   65,  326,   64,   73,
       62,   59,   67,   65,   69,   61,   66,  416,   65,   69,
       64,   67,   66,   70,   67,   71,   66,   70,   72,   71,
       74,   69,   76,   75,   66,   70,   75,   71,   81,   72,
       72,   77,   74,   76,   76,   75,   78,   79,   77,   78,
       81,   80,   84,   77,   82,   79,   80,   82,   83,   85,

       87,   78,   83,   84,   84,   87,   86,   79,   80,   82,
       86,   85,   87,   88,   83,   85,   89,  415,   90,   93,
      414,   91,   86,   88,   90,   88,   89,   91,   89,   92,
       94,   93,   95,   91,   92,   96,   90,   97,  413,   99,
      412,   92,   94,   95,   95,   99,   94,   96,   98,   97,
      100,   99,   98,   97,  100,  101,  102,  103,  411,  107,
      105,  101,  103,  102,   98,  105,  100,  101,  102,  110,
      106,  107,  105,  280,  103,  106,  108,  108,  108,  108,
      109,  110,  111,  112,  115,  110,  109,  106,  113,  280,
      113,  111,  109,  111,  111,  112,  115,  114,  116,  117,

      113,  114,  118,  410,  119,  121,  122,  120,  123,  121,
      116,  117,  122,  114,  118,  117,  119,  120,  122,  120,
      123,  121,  124,  125,  126,  127,  128,  138,  129,  226,
      226,  226,  138,  138,  124,  125,  126,  127,  128,  125,
      129,  130,  130,  129,  131,  130,  132,  409,  133,  134,
      134,  408,  135,  131,  136,  130,  131,  132,  132,  133,
      133,  137,  134,  135,  135,  137,  136,  139,  141,  142,
      143,  405,  404,  146,  148,  144,  145,  137,  142,  139,
      141,  142,  143,  144,  145,  146,  148,  149,  158,  146,
      148,  154,  403,  156,  157,  144,  145,  159,  157,  149,

      158,  161,  154,  154,  156,  156,  159,  162,  166,  159,
      157,  163,  161,  161,  171,  164,  163,  164,  162,  162,
      166,  172,  173,  163,  174,  175,  171,  181,  402,  164,
      171,  176,  182,  172,  173,  181,  174,  175,  173,  183,
      174,  176,  184,  176,  182,  187,  185,  184,  401,  188,
      187,  183,  183,  190,  191,  192,  195,  196,  185,  184,
      185,  188,  197,  198,  207,  190,  191,  192,  195,  196,
      207,  206,  195,  208,  197,  198,  207,  215,  197,  206,
      216,  215,  206,  208,  225,  208,  217,  237,  243,  396,
      236,  217,  216,  215,  245,  236,  216,  268,  217,  237,

      243,  225,  236,  225,  318,  395,  245,  394,  393,  268,
      344,  390,  318,  325,  325,  325,  325,  389,  344,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  374,  373,  372,  371,  370,  369,  368,  367,
      365,  364,  362,  360,  359,  356,  355,  354,  353,  352,
      351,  346,  345,  342,  341,  339,  338,  337,  336,  332,
      330,  329,  328,  327,  324,  323,  322,  321,  320,  319,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  301,  299,  298,  297,  296,  295,
      293,  292,  291,  290,  288,  286,  285,  284,  283,  282,

      281,  279,  277,  275,  274,  273,  272,  271,  270,  269,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  251,  250,  249,  248,  247,
      246,  244,  241,  240,  239,  238,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  224,  223,  222,  221,  220,
      219,  218,  213,  212,  211,  210,  209,  205,  204,  203,
      201,  200,  199,  194,  193,  189,  180,  179,  178,  177,
      170,  169,  168,  167,  165,  155,  104,   26,    5,    3,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "btasm_ubi.lex"
#line 2 "btasm_ubi.lex"

#include "btasm.h"
#include "y.tab.h"



void tok(char *tstr)
{
    if (tstr && tstr[0] != '!') {
        printf("%s\n",tstr);
    } else {
        printf("(%s:%s)\n",++tstr,yytext);
    }
}

void error(char *msg) 
{
    printf("%s",msg);
}

#line 789 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 25 "btasm_ubi.lex"



 /* ID/numbers */
#line 976 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 424 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 781 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "btasm_ubi.lex"
{ yylval.sVal = yytext; return ID; } //!
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "btasm_ubi.lex"
{ yylval.iVal = atoi(yytext); return INT; }
	YY_BREAK
/* Declarations */ 
case 3:
YY_RULE_SETUP
#line 33 "btasm_ubi.lex"
{ return VAR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "btasm_ubi.lex"
{ yylval.iVal = 3; return VARATTR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "btasm_ubi.lex"
{ yylval.iVal = 1; return VARATTR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "btasm_ubi.lex"
{ yylval.iVal = 2; return VARATTR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "btasm_ubi.lex"
{ return FUN; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "btasm_ubi.lex"
{ return STATE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "btasm_ubi.lex"
{ return FIRST_STATE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "btasm_ubi.lex"
{ return EVENT; }
	YY_BREAK
/* Conditional */
case 11:
YY_RULE_SETUP
#line 44 "btasm_ubi.lex"
{ return IF; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "btasm_ubi.lex"
{ yylval.iVal = 2; return COMP; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "btasm_ubi.lex"
{ yylval.iVal = 3; return COMP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "btasm_ubi.lex"
{ yylval.iVal = 0; return COMP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "btasm_ubi.lex"
{ return ELSE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "btasm_ubi.lex"
{ return END_IF; }
	YY_BREAK
/* Control flow */
case 17:
YY_RULE_SETUP
#line 52 "btasm_ubi.lex"
{ return GOTO; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "btasm_ubi.lex"
{ return END_FUNCTION; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "btasm_ubi.lex"
{ return END_STATE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "btasm_ubi.lex"
{ return END_EVENT; }
	YY_BREAK
/*TIMER*/
/* Event types */
case 21:
YY_RULE_SETUP
#line 59 "btasm_ubi.lex"
{ yylval.iVal = 0; return ETYPE; } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "btasm_ubi.lex"
{ yylval.iVal = 1; return ETYPE; } 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "btasm_ubi.lex"
{ yylval.iVal = 2; return ETYPE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "btasm_ubi.lex"
{ yylval.iVal = 9; return ETYPE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "btasm_ubi.lex"
{ yylval.iVal = 10; return ETYPE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "btasm_ubi.lex"
{ yylval.iVal = 11; return ETYPE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "btasm_ubi.lex"
{ yylval.iVal = 13; return ETYPE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "btasm_ubi.lex"
{ yylval.iVal = 14; return ETYPE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "btasm_ubi.lex"
{ yylval.iVal = 15; return ETYPE; }
	YY_BREAK
/* Mutation */
case 30:
YY_RULE_SETUP
#line 70 "btasm_ubi.lex"
{ return SET; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "btasm_ubi.lex"
{ return DEC; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "btasm_ubi.lex"
{ return INC; }
	YY_BREAK
/* HUD */
case 33:
YY_RULE_SETUP
#line 75 "btasm_ubi.lex"
{ return HUD_DIGIT; }
	YY_BREAK
/*OFF                     { return OFF; }*/
case 34:
YY_RULE_SETUP
#line 77 "btasm_ubi.lex"
{ return HUD_DIGIT_BLINK; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "btasm_ubi.lex"
{ return HUD_DIGIT_OFF; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "btasm_ubi.lex"
{ return HUD_JAUGE; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "btasm_ubi.lex"
{ return HUD_JAUGE_BLINK; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "btasm_ubi.lex"
{ return HUD_ICON_ON; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "btasm_ubi.lex"
{ return HUD_ICON_OFF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "btasm_ubi.lex"
{ yylval.iVal = 3; return ITYPE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "btasm_ubi.lex"
{ yylval.iVal = 2; return ITYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "btasm_ubi.lex"
{ return LED_ON; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "btasm_ubi.lex"
{ return LED_OFF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "btasm_ubi.lex"
{ return LED_INFINITE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "btasm_ubi.lex"
{ return ANIM; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "btasm_ubi.lex"
{ return ANIM_OFF; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 94 "btasm_ubi.lex"
{ return FLASH_ORANGE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 95 "btasm_ubi.lex"
{ return FLASH_GREEN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 96 "btasm_ubi.lex"
{ return FLASH_RED; }
	YY_BREAK
/* Sound/motor */
case 53:
YY_RULE_SETUP
#line 100 "btasm_ubi.lex"
{ return MOTOR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 101 "btasm_ubi.lex"
{ return SND; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 102 "btasm_ubi.lex"
{ return SND_PRIO; }
	YY_BREAK
/* Sounds */
case 56:
YY_RULE_SETUP
#line 105 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 114 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 115 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 116 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 117 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 118 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 119 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 120 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 121 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 122 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 123 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 124 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 125 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 126 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 127 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 128 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 129 "btasm_ubi.lex"
{ return RTYPE; }
	YY_BREAK
/* Vest */
case 81:
YY_RULE_SETUP
#line 134 "btasm_ubi.lex"
{ return HARNESS; }
	YY_BREAK
/* RFID */
case 82:
YY_RULE_SETUP
#line 138 "btasm_ubi.lex"
{ return RFID_SCAN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 139 "btasm_ubi.lex"
{ return RFID_TYPE_MAJOR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 140 "btasm_ubi.lex"
{ return RFID_TYPE_MINOR; }
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 142 "btasm_ubi.lex"
/* Ingore whitespace */
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 144 "btasm_ubi.lex"
{ printf("%d:Unrecognized language keyword:%s\n",yylineno,yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 145 "btasm_ubi.lex"
{ printf("%d:Illegal identifier:%s\n", yylineno,yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 147 "btasm_ubi.lex"
ECHO;
	YY_BREAK
#line 1512 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 424 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 424 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 423);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 147 "btasm_ubi.lex"



