#ifndef TOKTAB_H
#define TOKTAB_H
//Generated by toktab.pl
//Tokens for graph-generator
//btasm

char *toktab[512];

void filltoktab() {


	toktab[258] = "GOTO";
	toktab[259] = "SET";
	toktab[260] = "SET_HARNESS";
	toktab[261] = "INC";
	toktab[262] = "DEC";
	toktab[263] = "HUD_DIGIT";
	toktab[264] = "HUD_DIGIT_BLINK";
	toktab[265] = "HUD_DIGIT_OFF";
	toktab[266] = "HUD_JAUGE";
	toktab[267] = "HUD_ICON_ON";
	toktab[268] = "HUD_ICON_OFF";
	toktab[269] = "ITYPE";
	toktab[270] = "ANIM";
	toktab[271] = "SND";
	toktab[272] = "LED_ON";
	toktab[273] = "FLASH_ORANGE";
	toktab[274] = "FLASH_RED";
	toktab[275] = "FLASH_GREEN";
	toktab[276] = "IR";
	toktab[277] = "MOTOR";
	toktab[278] = "STATE";
	toktab[279] = "FIRST_STATE";
	toktab[280] = "END_STATE";
	toktab[281] = "EVENT";
	toktab[282] = "END_EVENT";
	toktab[283] = "FUN";
	toktab[284] = "END_FUNCTION";
	toktab[285] = "IF";
	toktab[286] = "ELSE";
	toktab[287] = "END_IF";
	toktab[288] = "VAR";
	toktab[289] = "SEQ";
	toktab[290] = "HUD_JAUGE_BLINK";
	toktab[291] = "CONFIG";
	toktab[292] = "SEND";
	toktab[293] = "RECEIVE";
	toktab[294] = "LED_OFF";
	toktab[295] = "LED_INFINITE";
	toktab[296] = "ANIM_OFF";
	toktab[297] = "SND_PRIO";
	toktab[298] = "HARNESS";
	toktab[299] = "RFID_SCAN";
	toktab[300] = "RFID_TYPE_MAJOR";
	toktab[301] = "RFID_TYPE_MINOR";
	toktab[302] = "INT";
	toktab[303] = "RTYPE";
	toktab[304] = "COMP";
	toktab[305] = "VARATTR";
	toktab[306] = "ETYPE";
	toktab[307] = "ID";
}
 #endif